#### Task 3: Import NumPy

This one is easy - just import the package 😄. Make sure to follow the conventions, though!

In [1]:
# Your code here
import numpy as np

#### Task 4: Python vs NumPy

Use pure Python and `numpy` to create a Python list/`numpy`:

- array of $10$ zeros;
- array of $10$ ones;
- array of $10$ fives;
- array of $10$ zeroes, the fifth value of which is $1$;
- array of all the integers from $10$ to $50$;
- array of all the even integers from $10$ to $50$;
- array that is the reversal of the list `[1, 2, 3]` (save these values in an object and use both methods to reverse that object);
- a 3x3 matrix with values ranging from $0$ to $8$;
- a 3x3 identity matrix;
- a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [24]:
# Your code here
print("\nArray of 10 zeros")
py_zeros = [0 for i in range(10)]
print(py_zeros)
np_zeros = np.zeros(10)
print(np_zeros)

print("\nArray of 10 ones")
py_ones = [1 for i in range(10)]
print(py_ones)
np_ones = np.ones(10)
print(np_ones)

print("\nArray of 10 fives")
py_fives = [5 for i in range(10)]
print(py_fives)
np_fives = np.full(10, 5)
print(np_fives)

print("\nArray of 10 zeros the fifth is 1")
py_zeros_with_one = [0 for i in range(10)]
py_zeros_with_one[5] = 1
print(py_zeros_with_one)
np_zeros_with_one = np.eye(1, 10, 5)
print(np_zeros_with_one)

print("\nArray of integers from 10 to 50")
py_ten_to_fifty = [i for i in range(10, 51)]
print(py_ten_to_fifty)
np_ten_to_fifty = np.arange(10, 51)
print(np_ten_to_fifty)

print("\nArray of even integers from 10 to 50")
py_even_ten_to_fifty = [i for i in range(10, 51, 2)]
print(py_even_ten_to_fifty)
np_even_ten_to_fifty = np.arange(10, 51, 2)
print(np_even_ten_to_fifty)

print("\nReversal of [1, 2, 3]")

py_three_to_one = [1, 2, 3]
py_three_to_one.reverse()
print(py_three_to_one)
one_to_three = [1, 2, 3]
np_three_to_one = np.flip(one_to_three)
print(np_three_to_one)

print("\n3x3 Matrix from 0 to 8")
py_zero_to_eight = [[j + 3 * i for j in range(3)] for i in range(3)]
print(py_zero_to_eight)
np_zero_to_eight = np.arange(9).reshape(3, 3)
print(np_zero_to_eight)

print("\n3x3 Identity matrix")
py_identity = [[int(i == j) for j in range(3)] for i in range(3)]
print(py_identity)
np_identity = np.identity(3)
print(np_identity)

print("\nMatrix with 1 to 4 below the diagonal")
py_one_to_four_below_diag = [[(i - j == 1) * (j + 1) for j in range(5)]
                             for i in range(5)]
print(py_one_to_four_below_diag)

np_one_to_four_below_diag = np.zeros((5, 5))
for i in range(4):
    np_one_to_four_below_diag[i + 1][i] = i + 1
print(np_one_to_four_below_diag)


Array of 10 zeros
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[5 5 5 5 5 5 5 5 5 5]

Array of 10 zeros the fifth is 1
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

Array of integers from 10 to 50
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Array of even integers from 10 to 50
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Reversal of [1, 2, 3]
[3, 2, 1]
[3 2 1]

3x3 Matrix from 0 to 8
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix
[[1, 0

In [25]:
# Expected result

#### Task 5: Using only NumPy:

1. Create a 5x5 array with $1$ on the border and $0$ inside.
2. Add a border filled with $0$'s on the two sides of an array `[1, 2, 3]`.
3. Create an array of $20$ equally spaced numbers between $0$ and $1$.
4. Create the following matrix:

```text
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

5. Find the indices of the non-zero elements in `[1, 2, 0, 0, 4, 0]`.

In [38]:
# Your code here
border_ones = np.full((3, 3), -1)
border_ones = np.pad(border_ones, 1)
border_ones += 1

print("Create a 5x5 array with 1 on the border and 0 inside")
print(border_ones)

arr = np.arange(1, 4)
arr = np.pad(arr, 1)
print("Add a border filled with '0s on the two sides of an array [1, 2, 3]")
print(arr)

arr = np.linspace(0, 1, 20)
print("Create an array of 20 equally spaced numbers between 0 and 1")
print(arr)

arr = np.arange(0.01, 1.01, .01).reshape((10, 10))
print("Recreation of the matrix")
print(arr)

arr = [1, 2, 0, 0, 4, 0]
indices_of_non_zero = np.argwhere(arr).T
print("Find the indices of the non-zero elements in [1, 2, 0, 0, 4, 0]")
print(indices_of_non_zero)

Create a 5x5 array with 1 on the border and 0 inside
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
Add a border filled with '0s on the two sides of an array [1, 2, 3]
[0 1 2 3 0]
Create an array of 20 equally spaced numbers between 0 and 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0

In [ ]:
# Expected result

Create a 5x5 array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Add a border filled with '0s on the two sides of an array [1, 2, 3]
[0 1 2 3 0]

Create an array of 20 equally spaced numbers between 0 and 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0

#### Task 6: Use NumPy to generate:

- a random number between 0 and 1;
- an array of 25 random numbers sampled from a standard normal distribution;
- a 3x3x3 array with random values drawn from the uniform distribution;
- a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values;
- a random array with values drawn from the uniform distribution of size 30 and find the mean value;
- and multiply a 5x3 matrix by a 3x2 matrix.

**Note**: Your values should be different from the one shown below due to randomness.

In [43]:
# Your code here
randnum = np.random.rand(1)
print("a random number between 0 and 1")
print(randnum)

randarr = np.random.normal(size=25)
print(
    "an array of 25 random numbers sampled from a standard normal distribution"
)
print(randarr)

uniformarr = np.random.uniform(size=(3, 3, 3))
print("a 3x3x3 array with random values drawn from the uniform distribution")
print(uniformarr)

uniformarr = np.random.uniform(size=(10, 10))
print(
    "a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values"
)
print("The array:")
print(uniformarr)
print(f"Min and max values: {(uniformarr.min(), uniformarr.max())}")

uniformarr = np.random.uniform(size=30)
print(
    "a random array with values drawn from the uniform distribution of size 30 and find the mean value"
)
print("The array:")
print(uniformarr)
print(f"Its mean: {uniformarr.mean()}")

matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
print("multiplying a 5x3 matrix by a 3x2 matrix each with random values")
print(matrix1 @ matrix2)

a random number between 0 and 1
[0.73326224]
an array of 25 random numbers sampled from a standard normal distribution
[ 1.38359398 -0.50560085  2.6450223  -1.41613474  0.88334661 -1.10683434
  0.09396385  1.09723361  0.0178362  -0.7131417  -1.01765131  0.87046194
  0.69193637  1.28999815  0.40865184 -2.28683401  0.04286338 -0.05611687
  0.92145105  0.92678195 -0.30357592  1.40408672  0.48006314 -1.02557269
 -0.7832431 ]
a 3x3x3 array with random values drawn from the uniform distribution
[[[0.97856065 0.6021936  0.53232529]
  [0.04318594 0.6815125  0.96170552]
  [0.01900623 0.48780488 0.97349714]]

 [[0.38400647 0.55255246 0.68564779]
  [0.77915923 0.17586615 0.86962142]
  [0.81752589 0.9951766  0.9042972 ]]

 [[0.47644168 0.42918596 0.99007614]
  [0.69193859 0.07847317 0.89222134]
  [0.01949413 0.55887267 0.38618321]]]
a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values
The array:
[[0.60597651 0.33176015 0.06696987 0.90733067 0

In [ ]:
# Expected result

a random number between 0 and 1
0.3302392460734943

an array of 25 random numbers sampled from a standard normal distribution
[-0.85565418  0.4592446   0.90183199  0.53932203  0.04080838 -0.4210383
  1.00116207  0.08236895  0.08804113  0.11602095 -0.87912022  0.37818965
 -0.39515241  0.81614267 -0.73406941 -0.49574339 -0.4419727   2.66688758
  1.69571397  0.83054423  1.2732238  -1.55596546 -0.16924736 -1.12509893
 -0.05953329]

a 3x3x3 array with random values drawn from the uniform distribution
[[[0.42054451 0.27312439 0.95347927]
  [0.55134496 0.6235185  0.72550932]
  [0.37674019 0.56769456 0.58315167]]

 [[0.96651862 0.81392441 0.26927728]
  [0.758904   0.75618622 0.35625557]
  [0.12351087 0.43525117 0.68535189]]

 [[0.06672974 0.36402819 0.166292  ]
  [0.95530001 0.84750085 0.25077735]
  [0.95153091 0.8262242  0.86062338]]]

a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values
The array:
[[0.32519229 0.66282593 0.61989954 0.07

#### Task 7: Write code that uses the below matrix to reproduce the expected output

In [44]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
# Your code here
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [50]:
# Expected result

In [57]:
# Your code here
print(f"{mat.dtype}({mat[3,4]})")

int64(20)


In [ ]:
# Expected result

np.int64(20)

In [66]:
# Your code here
print(mat[(mat%5 == 2) & (mat < 15)].reshape(-1,1))

[[ 2]
 [ 7]
 [12]]


In [67]:
# Expected result

In [68]:
# Your code here
print(mat[4, :])

[21 22 23 24 25]


In [ ]:
# Expected result

array([21, 22, 23, 24, 25])

In [70]:
# Your code here
print(mat[3:, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# Expected result

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Task 8: Continue using the matrix `mat` to calculate the:

- sum of its values;
- standard deviation of its values;
- the sum of all the columns;

In [71]:
# Your code here
mat.sum()

np.int64(325)

In [ ]:
# Expected result

np.int64(325)

In [72]:
# Your code here
mat.std()

np.float64(7.211102550927978)

In [ ]:
# Expected result

np.float64(7.211102550927978)

In [74]:
# Your code here
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected result

array([55, 60, 65, 70, 75])

#### Task 9: Let's practice composing operations:

1. Create a 1D array of random integers between $0$ and $9$. Negate all numbers that fall in the interval $[3, 8]$.
2. Create a random array with floating point values of size $10$ and sort it.
3. Create random vector of values drawn from the uniform distribution of size $10$ and replace the maximum value with $0$.

In [83]:
# Your code here
arr = np.random.randint(0, 10, 10)
arr[(arr >= 3) & (arr <= 8)] *= -1
print(arr)

[ 9 -3 -6  0 -5  1 -5 -7 -4  9]


In [ ]:
# Expected result

array([-8,  0, -4, -8, -4,  2, -5, -5,  9, -7])

In [84]:
# Your code here
arr = np.random.rand(10)
arr = np.sort(arr)
print(arr)

[0.02290363 0.05319234 0.15468097 0.31388889 0.38665158 0.55537681
 0.66774159 0.69550386 0.74813207 0.96045433]


In [85]:
# Expected result

In [87]:
# Your code here
arr = np.random.uniform(size=10)
print(f"The array: {arr}")
arr[arr.argmax()] = 0
print(f"Result: {arr}")

The array: [0.36438927 0.78160729 0.74076464 0.80638285 0.04941895 0.35816931
 0.60172898 0.02922176 0.28717988 0.65971845]
Result: [0.36438927 0.78160729 0.74076464 0.         0.04941895 0.35816931
 0.60172898 0.02922176 0.28717988 0.65971845]


In [88]:
# Expected result

#### Task 10: Reproducibility

When training models, it's often important to generate the same random numbers every time the application is run, even if the machine changes. This ability helps us remove the possibility of creating the situation: *Well, it works on my machine...*.

Our code should work on all machines and produce the same results across different runs.

Go through the [documentation](https://numpy.org/doc/stable/reference/module_structure.html) and answer the below question.

How can we ensure that we always get the same random numbers (even if we switch machines)? Give two examples.

> **Your answer**: We should set a specific seed and use it in every occasion. We can do this 2 ways:

np.random.seed(n)

or 

rng = np.random.default_rng(seed = n)

and after that use rng instead of np.random